// AFAB Nation Radio catalog.
//
// Single source of truth for every song on the site. The Music page and the
// Radio "Now Playing" section both render generically from this array --
// there is no per-song code anywhere else, and the renderer does not inspect
// title/artist/description/lyrics content. To add a song, add an entry here;
// to unpublish one without deleting it, set published:false.
//
// Fields:
//   id            unique slug -- used for transcript panel ids and post links
//   title         song title (required -- entries without one are skipped)
//   artist        display artist name
//   audio         path to the audio file, or "" if no audio yet
//   cover         path to real cover art, or "" to fall back to coverText
//   coverText     short text shown on the placeholder cover when no cover image
//   genre         array of strings, e.g. ["Arena Rock", "Anthem"] -- optional
//   releaseDate   ISO date string ("2026-08-25") -- optional
//   description   one-line blurb shown on the card -- optional
//   explicit      true/false, shows an "Explicit" badge
//   featured      true/false, shows a "Featured" badge
//   published     false hides the track from the site entirely (default true)
//   transcript        full lyrics/transcript text, or "" if not written yet
//   transcriptStatus  "pending" or "complete" -- controls the transcript UI copy

window.AFAB_CATALOG = [
  {
    id: "clams-not-pronouns",
    title: "Clams Not Pronouns",
    artist: "Mari Cruz",
    audio: "audio/clams-not-pronouns.mp3",
    cover: "",
    coverText: "CLAMS",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "xx-is-not-a-feeling",
    title: "XX Is Not a Feeling!",
    artist: "Mari Cruz",
    audio: "audio/xx-is-not-a-feeling.mp3",
    cover: "",
    coverText: "XX",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "real-females-dont-disappear",
    title: "Real Females Don't Disappear",
    artist: "Mari Cruz",
    audio: "audio/real-females-dont-disappear.mp3",
    cover: "",
    coverText: "REAL\nFEMALES",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "keep-your-male-privilege-out-of-womens-spaces",
    title: "Keep Your Male Privilege Out of Women's Spaces",
    artist: "Mari Cruz",
    audio: "audio/keep-your-male-privilege-out-of-womens-spaces.mp3",
    cover: "",
    coverText: "KEEP\nOUT",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "1st-edition",
    title: "1st Edition",
    artist: "Mari Cruz",
    audio: "audio/1st-edition.mp3",
    cover: "",
    coverText: "1ST\nEDITION",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "wrong-door-amigo",
    title: "Wrong Door, Amigo",
    artist: "Mari Cruz",
    audio: "audio/wrong-door-amigo.mp3",
    cover: "",
    coverText: "WRONG\nDOOR",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "define-it-or-draft-em",
    title: "Define It or Draft 'Em",
    artist: "Mari Cruz",
    audio: "audio/define-it-or-draft-em.mp3",
    cover: "",
    coverText: "DEFINE\nIT",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "afab-nation",
    title: "AFAB Nation",
    artist: "AFAB Nation",
    audio: "audio/afab-nation.mp3",
    cover: "",
    coverText: "AFAB\nNATION",
    genre: ["Arena Rock", "Anthem"],
    releaseDate: "2026-08-25",
    description: "",
    explicit: false,
    featured: true,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "afab-nation-espanol",
    title: "AFAB Nation (Español)",
    artist: "AFAB Nation",
    audio: "audio/afab-nation-espanol.mp3",
    cover: "",
    coverText: "AFAB\nNATION",
    genre: ["Arena Rock", "Anthem"],
    releaseDate: "2026-08-25",
    description: "",
    explicit: false,
    featured: true,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "chicks-dont-have-sticks",
    title: "Chicks Don't Have Sticks",
    artist: "Mari Cruz",
    audio: "audio/chicks-dont-have-sticks.mp3",
    cover: "",
    coverText: "CHICKS",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "cross-gender-ideation",
    title: "Cross-Gender Ideation",
    artist: "Mari Cruz",
    audio: "audio/cross-gender-ideation.mp3",
    cover: "",
    coverText: "CROSS-\nGENDER",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "i-identify-as-a-transwoman",
    title: "I Identify as a Transwoman",
    artist: "Mari Cruz",
    audio: "audio/i-identify-as-a-transwoman.mp3",
    cover: "",
    coverText: "I\nIDENTIFY",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "misogyny-in-a-dress-is-still-misogyny",
    title: "Misogyny in a Dress Is Still Misogyny",
    artist: "Mari Cruz",
    audio: "audio/misogyny-in-a-dress-is-still-misogyny.mp3",
    cover: "",
    coverText: "MISOGYNY\nIN A DRESS",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "afab-transwomen-lives-matter",
    title: "AFAB Transwomen Lives Matter",
    artist: "Mari Cruz",
    audio: "audio/afab-transwomen-lives-matter.mp3",
    cover: "",
    coverText: "AFAB\nTRANSWOMEN",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "congas-and-drumsticks",
    title: "Congas & Drumsticks",
    artist: "Mari Cruz",
    audio: "audio/congas-and-drumsticks.mp3",
    cover: "",
    coverText: "CONGAS",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "men-have-balls-women-have-ovaries",
    title: "Men Have Balls, Women Have Ovaries",
    artist: "Mari Cruz",
    audio: "audio/men-have-balls-women-have-ovaries.mp3",
    cover: "",
    coverText: "MEN\nWOMEN",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "skinwalking-xx",
    title: "Skinwalking XX",
    artist: "Mari Cruz",
    audio: "audio/skinwalking-xx.mp3",
    cover: "",
    coverText: "SKIN-\nWALKING",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "this-is-a-woman",
    title: "This Is a Woman",
    artist: "Mari Cruz",
    audio: "audio/this-is-a-woman.mp3",
    cover: "",
    coverText: "THIS IS\nA WOMAN",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "trans-the-antonym",
    title: "Trans: The Antonym",
    artist: "Mari Cruz",
    audio: "audio/trans-the-antonym.mp3",
    cover: "",
    coverText: "THE\nANTONYM",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  },
  {
    id: "you-give-womanhood-a-bad-name",
    title: "You Give Womanhood a Bad Name",
    artist: "Mari Cruz",
    audio: "audio/you-give-womanhood-a-bad-name.mp3",
    cover: "",
    coverText: "BAD\nNAME",
    genre: [],
    releaseDate: "",
    description: "",
    explicit: false,
    featured: false,
    published: true,
    transcript: "",
    transcriptStatus: "pending"
  }
];
